batch_size: 32
ckpt_path: ''
data_path: /datasets/ImageNet
dataset_name: imagenet
lr: 0.0002
lr_scheduler: MultiStepLR
milestones:
- 24
- 28
model_name: clip_vit_h14_dfn5b
num_epochs: 30
sae_ckpt_path: checkpoints/clip_vit_l14_datacomp_xl_s13b_b90k_imagenet_topk-spatial-64-30000_layer--1_lr_0.0002/last.ckpt
sae_hidden_dim: 30000
sae_k: 64
sae_layer_idx: -1
sae_token: cls
wandb_api_key: ''
wandb_project_name: train-sae-0
